import { useState } from "react";
import { Menu, ChevronDown, Search, Bell, ArrowRight } from "lucide-react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import { useDemo, useStudent } from "../../lib/store";
import Modal from "../ui/Modal";
import Button from "../ui/Button";
export default function Header({ onMenu }: { onMenu: () => void }) {
  const { state, update, reset } = useDemo(); const student=useStudent(); const [profile,setProfile]=useState(false),[confirm,setConfirm]=useState(false),[notifications,setNotifications]=useState(false),[search,setSearch]=useState(''); const location=useLocation(),navigate=useNavigate();
  const assignments=state.assignments.filter(a=>state.role==='faculty'||a.studentId===student.id); const segment=location.pathname.split('/')[2]; const title:Record<string,string>={dashboard:state.role==='faculty'?'Class Overview':'Dashboard',library:'Digital Library',quiz:'Knowledge Check','learning-path':'Learning Path',assistant:'Learning Assistant',progress:'My Progress',assignments:'Assigned Resources',students:'Student Insights',resources:'Resource Management'};
  return <header className="header"><div className="header-left"><button className="icon-btn mobile-menu" onClick={onMenu} aria-label="Open navigation"><Menu/></button><span className="breadcrumb"><Link to={`/${state.role}/dashboard`}>{state.role==='faculty'?'Professor':'Student'}</Link><span>/</span><strong>{title[segment]||'Workspace'}</strong></span></div><div className="header-actions"><form className="header-search" onSubmit={e=>{e.preventDefault();navigate(`${state.role==='faculty'?'/faculty/resources':'/student/library'}?q=${encodeURIComponent(search)}`)}}><Search size={17}/><input aria-label="Search learning resources" placeholder="Search resources..." value={search} onChange={e=>setSearch(e.target.value)}/><kbd>↵</kbd></form><span className="header-divider"/><button className="icon-btn notification-btn" aria-label="View assignments and notifications" onClick={()=>setNotifications(true)}><Bell size={20}/>{assignments.length>0&&<i/>}</button><button className="profile-trigger" onClick={()=>setProfile(true)} aria-label="Open demo profile menu"><span className="avatar">{state.role==='faculty'?'PR':student.initials}</span><span>{state.role==='faculty'?'Professor demo':student.name}<small>{state.role==='faculty'?'Professor':'Student'}</small></span><ChevronDown size={15}/></button></div>
  {profile&&<Modal title="Your demo workspace" onClose={()=>setProfile(false)}><p className="muted">{state.role==='student'?'Demo access only. Choose a profile to explore its saved learning journey.':'Professor demo identity. Open Student Insights to inspect individual learners.'} These controls demonstrate navigation; they are not authentication or security.</p>{state.role==='student'&&<label className="field">Student profile<select value={state.profileId} onChange={e=>update(s=>({...s,profileId:e.target.value}),'Demo profile changed')}>{state.students.map(s=><option value={s.id} key={s.id}>{s.name} · {s.classId}</option>)}</select></label>}<div className="modal-actions"><Link className="btn btn-secondary" to="/" onClick={()=>setProfile(false)}>Welcome page</Link><Button variant="danger" onClick={()=>{setProfile(false);setConfirm(true)}}>Reset demo data</Button></div></Modal>}
  {confirm&&<Modal title="Reset your demo?" onClose={()=>setConfirm(false)}><p>This removes saved attempts, bookmarks, assignments, and resource edits in this browser, then restores the synthetic demo profiles.</p><div className="modal-actions"><Button variant="secondary" onClick={()=>setConfirm(false)}>Keep my data</Button><Button variant="danger" onClick={()=>{reset();setConfirm(false);navigate('/')}}>Reset demo data</Button></div></Modal>}
  {notifications&&<Modal title={state.role==='faculty'?'Class assignments':'Your assignments'} onClose={()=>setNotifications(false)}>{assignments.length?assignments.map(a=>{const r=state.resources.find(r=>r.id===a.resourceId);return <Link key={a.id} className="assignment-row" to={state.role==='faculty'?`/faculty/students/${a.studentId}`:`/student/library/${a.resourceId}`} onClick={()=>setNotifications(false)}><span>{r?.title??'Resource unavailable'}<small>{state.role==='faculty'?`Assigned to ${state.students.find(s=>s.id===a.studentId)?.name}`:'Assigned by Professor'}{r?.archived?' · Archived resource':''}</small></span><ArrowRight size={18}/></Link>}):<p className="muted">{state.role==='faculty'?'No class assignments yet. Open Student Insights to assign a resource.':"You're all caught up. Resources assigned by your Professor will appear here."}</p>}</Modal>}</header>;
}
